

import sys

from PyQt4 import QtCore, QtGui
from PyQt4.Qt import QWidget, Qt
from PyQt4.QtGui import QWidget, QApplication, QTreeView, QListView, QTextEdit, \
                        QSplitter, QHBoxLayout, QVBoxLayout, QSizeGrip


try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.setupUi(self)
        
        
        self.scrollArea_5.setWindowFlags(Qt.SubWindow)
        qSizeGrip = QSizeGrip(self.scrollArea_5)
        self.verticalLayout_5.addWidget(qSizeGrip)
        
        """layout = QtGui.QHBoxLayout()
        layout.addWidget(qSizeGrip)
        self.setLayout(layout)"""
        
        
        """layout = QtGui.QHBoxLayout()
        layout.addWidget(self.scrollArea_5)
        self.scrollArea_5.setLayout(layout)"""
        
        # connect signals
        self.hide_and_show(self.pushButton_31, self.frame)
        self.hide_and_show(self.pushButton_81, self.plainTextEdit_12)
        self.hide_and_show(self.pushButton_85, self.plainTextEdit_11)
        
    def hide_and_show(self, pushButton, receiver):        
        def lambda_hide_and_show():
            if receiver.isVisible():
                receiver.hide()
                pushButton.setText("►" + pushButton.text()[1:])
            else:
                receiver.show()
                pushButton.setText("▼" + pushButton.text()[1:])
            
            parent = receiver.parentWidget()
            while(parent):
                print(parent.objectName() + " : " + parent.layout().objectName())
                parent.adjustSize()
                parent = parent.parentWidget()
                
        pushButton.clicked.connect(lambda_hide_and_show)
        # text = "►" + pushButton.text()[1:] if receiver.isVisible() else "▼" + pushButton.text()[1:]
        # print(text)
        # pushButton.setText(text)
        
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(607, 482)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setMouseTracking(True)
        Form.setInputMethodHints(QtCore.Qt.ImhNone)
        self.verticalLayout_6 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.frame_3 = QtGui.QFrame(Form)
        self.frame_3.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(200, 40))
        self.frame_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.frame_3.setAcceptDrops(True)
        self.frame_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setLineWidth(1)
        self.frame_3.setMidLineWidth(0)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_14 = QtGui.QFrame(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 21))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 21))
        self.frame_14.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_14.setObjectName(_fromUtf8("frame_14"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.frame_14)
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.pushButton_31 = QtGui.QPushButton(self.frame_14)
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.horizontalLayout_17.addWidget(self.pushButton_31)
        self.line_8 = QtGui.QFrame(self.frame_14)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout_17.addWidget(self.line_8)
        self.frame_15 = QtGui.QFrame(self.frame_14)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_15.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_15.setObjectName(_fromUtf8("frame_15"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.frame_15)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.pushButton_32 = QtGui.QPushButton(self.frame_15)
        self.pushButton_32.setObjectName(_fromUtf8("pushButton_32"))
        self.horizontalLayout_18.addWidget(self.pushButton_32)
        self.pushButton_33 = QtGui.QPushButton(self.frame_15)
        self.pushButton_33.setObjectName(_fromUtf8("pushButton_33"))
        self.horizontalLayout_18.addWidget(self.pushButton_33)
        self.pushButton_34 = QtGui.QPushButton(self.frame_15)
        self.pushButton_34.setObjectName(_fromUtf8("pushButton_34"))
        self.horizontalLayout_18.addWidget(self.pushButton_34)
        self.horizontalLayout_17.addWidget(self.frame_15)
        self.verticalLayout_3.addWidget(self.frame_14)
        self.frame = QtGui.QFrame(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.line_3 = QtGui.QFrame(self.frame)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_5.addWidget(self.line_3)
        self.scrollArea_5 = QtGui.QScrollArea(self.frame)
        self.scrollArea_5.setFrameShape(QtGui.QFrame.Box)
        self.scrollArea_5.setLineWidth(1)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName(_fromUtf8("scrollArea_5"))
        self.scrollAreaWidgetContents_5 = QtGui.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 563, 193))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_5.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_5.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.frame_54 = QtGui.QFrame(self.scrollAreaWidgetContents_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_54.sizePolicy().hasHeightForWidth())
        self.frame_54.setSizePolicy(sizePolicy)
        self.frame_54.setMinimumSize(QtCore.QSize(0, 21))
        self.frame_54.setMaximumSize(QtCore.QSize(16777215, 21))
        self.frame_54.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_54.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_54.setObjectName(_fromUtf8("frame_54"))
        self.horizontalLayout_57 = QtGui.QHBoxLayout(self.frame_54)
        self.horizontalLayout_57.setSpacing(6)
        self.horizontalLayout_57.setMargin(0)
        self.horizontalLayout_57.setObjectName(_fromUtf8("horizontalLayout_57"))
        self.pushButton_81 = QtGui.QPushButton(self.frame_54)
        self.pushButton_81.setObjectName(_fromUtf8("pushButton_81"))
        self.horizontalLayout_57.addWidget(self.pushButton_81)
        self.line_28 = QtGui.QFrame(self.frame_54)
        self.line_28.setFrameShape(QtGui.QFrame.VLine)
        self.line_28.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_28.setObjectName(_fromUtf8("line_28"))
        self.horizontalLayout_57.addWidget(self.line_28)
        self.frame_55 = QtGui.QFrame(self.frame_54)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_55.sizePolicy().hasHeightForWidth())
        self.frame_55.setSizePolicy(sizePolicy)
        self.frame_55.setMinimumSize(QtCore.QSize(180, 0))
        self.frame_55.setMaximumSize(QtCore.QSize(180, 16777215))
        self.frame_55.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_55.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_55.setObjectName(_fromUtf8("frame_55"))
        self.horizontalLayout_58 = QtGui.QHBoxLayout(self.frame_55)
        self.horizontalLayout_58.setSpacing(6)
        self.horizontalLayout_58.setMargin(0)
        self.horizontalLayout_58.setObjectName(_fromUtf8("horizontalLayout_58"))
        self.label = QtGui.QLabel(self.frame_55)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_58.addWidget(self.label)
        self.dateEdit = QtGui.QDateEdit(self.frame_55)
        self.dateEdit.setDate(QtCore.QDate(2015, 2, 13))
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_58.addWidget(self.dateEdit)
        self.radioButton_15 = QtGui.QRadioButton(self.frame_55)
        self.radioButton_15.setMinimumSize(QtCore.QSize(40, 0))
        self.radioButton_15.setMaximumSize(QtCore.QSize(40, 16777215))
        self.radioButton_15.setObjectName(_fromUtf8("radioButton_15"))
        self.horizontalLayout_58.addWidget(self.radioButton_15)
        self.pushButton_82 = QtGui.QPushButton(self.frame_55)
        self.pushButton_82.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton_82.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_82.setObjectName(_fromUtf8("pushButton_82"))
        self.horizontalLayout_58.addWidget(self.pushButton_82)
        self.horizontalLayout_57.addWidget(self.frame_55)
        self.verticalLayout_14.addWidget(self.frame_54)
        self.plainTextEdit_12 = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents_5)
        self.plainTextEdit_12.setObjectName(_fromUtf8("plainTextEdit_12"))
        self.verticalLayout_14.addWidget(self.plainTextEdit_12)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_5.addWidget(self.scrollArea_5)
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_5.addWidget(self.line_2)
        self.scrollArea_4 = QtGui.QScrollArea(self.frame)
        self.scrollArea_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_4.setLineWidth(1)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 565, 194))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_4.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_4.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.frame_58 = QtGui.QFrame(self.scrollAreaWidgetContents_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_58.sizePolicy().hasHeightForWidth())
        self.frame_58.setSizePolicy(sizePolicy)
        self.frame_58.setMinimumSize(QtCore.QSize(0, 21))
        self.frame_58.setMaximumSize(QtCore.QSize(16777215, 21))
        self.frame_58.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_58.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_58.setObjectName(_fromUtf8("frame_58"))
        self.horizontalLayout_61 = QtGui.QHBoxLayout(self.frame_58)
        self.horizontalLayout_61.setSpacing(6)
        self.horizontalLayout_61.setMargin(0)
        self.horizontalLayout_61.setObjectName(_fromUtf8("horizontalLayout_61"))
        self.pushButton_85 = QtGui.QPushButton(self.frame_58)
        self.pushButton_85.setObjectName(_fromUtf8("pushButton_85"))
        self.horizontalLayout_61.addWidget(self.pushButton_85)
        self.line_30 = QtGui.QFrame(self.frame_58)
        self.line_30.setFrameShape(QtGui.QFrame.VLine)
        self.line_30.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_30.setObjectName(_fromUtf8("line_30"))
        self.horizontalLayout_61.addWidget(self.line_30)
        self.frame_59 = QtGui.QFrame(self.frame_58)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_59.sizePolicy().hasHeightForWidth())
        self.frame_59.setSizePolicy(sizePolicy)
        self.frame_59.setMinimumSize(QtCore.QSize(180, 0))
        self.frame_59.setMaximumSize(QtCore.QSize(180, 16777215))
        self.frame_59.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_59.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_59.setObjectName(_fromUtf8("frame_59"))
        self.horizontalLayout_62 = QtGui.QHBoxLayout(self.frame_59)
        self.horizontalLayout_62.setSpacing(6)
        self.horizontalLayout_62.setMargin(0)
        self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        self.label_2 = QtGui.QLabel(self.frame_59)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_62.addWidget(self.label_2)
        self.dateEdit_2 = QtGui.QDateEdit(self.frame_59)
        self.dateEdit_2.setDate(QtCore.QDate(2015, 2, 13))
        self.dateEdit_2.setObjectName(_fromUtf8("dateEdit_2"))
        self.horizontalLayout_62.addWidget(self.dateEdit_2)
        self.radioButton_17 = QtGui.QRadioButton(self.frame_59)
        self.radioButton_17.setMinimumSize(QtCore.QSize(40, 0))
        self.radioButton_17.setMaximumSize(QtCore.QSize(40, 16777215))
        self.radioButton_17.setObjectName(_fromUtf8("radioButton_17"))
        self.horizontalLayout_62.addWidget(self.radioButton_17)
        self.pushButton_86 = QtGui.QPushButton(self.frame_59)
        self.pushButton_86.setMinimumSize(QtCore.QSize(20, 0))
        self.pushButton_86.setMaximumSize(QtCore.QSize(20, 16777215))
        self.pushButton_86.setObjectName(_fromUtf8("pushButton_86"))
        self.horizontalLayout_62.addWidget(self.pushButton_86)
        self.horizontalLayout_61.addWidget(self.frame_59)
        self.verticalLayout_13.addWidget(self.frame_58)
        self.plainTextEdit_11 = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents_4)
        self.plainTextEdit_11.setObjectName(_fromUtf8("plainTextEdit_11"))
        self.verticalLayout_13.addWidget(self.plainTextEdit_11)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_5.addWidget(self.scrollArea_4)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addWidget(self.frame_3)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.pushButton_34, QtCore.SIGNAL(_fromUtf8("clicked()")), self.frame.close)
        QtCore.QObject.connect(self.pushButton_34, QtCore.SIGNAL(_fromUtf8("clicked()")), self.frame_3.resize)
        QtCore.QObject.connect(self.pushButton_86, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_2.close)
        QtCore.QObject.connect(self.pushButton_86, QtCore.SIGNAL(_fromUtf8("clicked()")), self.scrollArea_4.close)
        QtCore.QObject.connect(self.pushButton_82, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_3.close)
        QtCore.QObject.connect(self.pushButton_82, QtCore.SIGNAL(_fromUtf8("clicked()")), self.scrollArea_5.close)
        QtCore.QObject.connect(self.pushButton_34, QtCore.SIGNAL(_fromUtf8("clicked()")), self.frame_3.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Task Manager", None))
        self.pushButton_31.setText(_translate("Form", "▼ Project 0", None))
        self.pushButton_32.setText(_translate("Form", "+P", None))
        self.pushButton_33.setText(_translate("Form", "+T", None))
        self.pushButton_34.setText(_translate("Form", "x", None))
        self.pushButton_81.setText(_translate("Form", "▼ Task 0", None))
        self.label.setText(_translate("Form", "DD", None))
        self.radioButton_15.setText(_translate("Form", "MaI", None))
        self.pushButton_82.setText(_translate("Form", "x", None))
        self.pushButton_85.setText(_translate("Form", "▼ Task 0", None))
        self.label_2.setText(_translate("Form", "DD", None))
        self.radioButton_17.setText(_translate("Form", "MaI", None))
        self.pushButton_86.setText(_translate("Form", "x", None))

if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    ex = Ui_Form()
    ex.show()
    sys.exit(app.exec_())